#ifndef SMARTRF_CC1101_H
#define SMARTRF_CC1101_H

#define SMARTRF_RADIO_CC1101
#define SMARTRF_SETTING_IOCFG2     0x2E
#define SMARTRF_SETTING_IOCFG0     0x0D
#define SMARTRF_SETTING_FIFOTHR    0x47
#define SMARTRF_SETTING_PKTCTRL0   0x32
#define SMARTRF_SETTING_FSCTRL1    0x06
#define SMARTRF_SETTING_FREQ2      0x10
#define SMARTRF_SETTING_FREQ1      0xB0
#define SMARTRF_SETTING_FREQ0      0x71
#define SMARTRF_SETTING_MDMCFG4    0xF5
#define SMARTRF_SETTING_MDMCFG3    0xB3
#define SMARTRF_SETTING_MDMCFG2    0x30
#define SMARTRF_SETTING_DEVIATN    0x15
#define SMARTRF_SETTING_MCSM1      0x3C
#define SMARTRF_SETTING_MCSM0      0x18
#define SMARTRF_SETTING_FOCCFG     0x16
#define SMARTRF_SETTING_BSCFG      0x6C
#define SMARTRF_SETTING_AGCCTRL2   0x43
#define SMARTRF_SETTING_AGCCTRL1   0x40
#define SMARTRF_SETTING_AGCCTRL0   0x91
#define SMARTRF_SETTING_FREND0     0x11
#define SMARTRF_SETTING_FSCAL3     0xE9
#define SMARTRF_SETTING_FSCAL2     0x2A
#define SMARTRF_SETTING_FSCAL1     0x00
#define SMARTRF_SETTING_FSCAL0     0x1F
#define SMARTRF_SETTING_TEST2      0x81
#define SMARTRF_SETTING_TEST1      0x35
#define SMARTRF_SETTING_TEST0      0x09

#endif /* SMARTRF_CC1101_H */
